services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=kaio_rx@hotmail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access-log"
    deploy:
      placement:
        constraints:
          - node.role == manager

      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-https@docker"
        - "traefik.http.routers.http-catchall.priority=1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vol_certificates:/etc/traefik/letsencrypt"
    networks:
      - public
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

  mongodb:
    image: mongo:7
    command: mongod --port 27017
    networks:
      - public
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb_data:/data/configdb
    environment:
      - PUID=1000
      - PGID=1000

    ports:
      - 27017:27017

    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.role == manager

      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

      resources:
        limits:
          cpus: "0.25"
          memory: 1024M

  postgres:
    image: postgres:16
    networks:
      - public

    entrypoint: docker-entrypoint.sh
    command: [postgres, --max_connections=200]

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=SENHA
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.role == manager

      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

      resources:
        limits:
          cpus: "0.25"
          memory: 1024M 


  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - public
    deploy:
        mode: global
        placement:
          constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.portainer.rule=Host(`panel.realmtech.cloud`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.priority=1"
        - "traefik.http.routers.portainer.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  public:
   external: true
   attachable: true
   name: public

volumes:
  postgres_data:
    external: true
    name: postgres_data
  mongodb_data:
    external: true
    name: mongodb_data
  mongodb_configdb_data:
    external: true
    name: mongodb_configdb_data
  portainer_data:
    external: true
    name: portainer_data
  vol_shared:
    external: true
    name: volume_swarm_shared
  vol_certificates:
    external: true
    name: volume_swarm_certificates

